; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "道路工程比赛抽签系统"
#define MyAppVersion "2.0.1"
#define MyAppPublisher "Zitai Wang"
#define MyAppURL "https://github.com/Jessssssseea/Contest-drawer-Roadworks"
#define MyAppExeName "道路工程比赛抽签系统.exe"
#expr EmitLanguagesSection

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{51BF1A49-39BF-43CD-822C-84F7B723FC81}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Contest drawer Roadworks
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=D:\daolugongcheng\version2.0.1\main.dist\LICENSE.txt
InfoBeforeFile=D:\daolugongcheng\version2.0.1\main.dist\README.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\daolugongcheng\version2.0.1\outinstall
OutputBaseFilename=Contest drawer Roadworks
SetupIconFile=D:\daolugongcheng\icon.ico
SolidCompression=yes
WizardStyle=modern windows11
PrivilegesRequired=admin

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
  ValueType: String; ValueName: "{app}\道路工程比赛抽签系统.exe"; ValueData: "RUNASADMIN"; \
  Flags: uninsdeletevalue uninsdeletekeyifempty

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\daolugongcheng\version2.0.1\main.dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\_hashlib.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\libcrypto-1_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\libeay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\msvcp140_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\python3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\python38.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5dbus.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5multimedia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5printsupport.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5qml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5qmlmodels.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5quick.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5websockets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\qt5widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\select.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\ssleay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\unicodedata.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\vcruntime140_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\道路工程训练地图新.tif"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\道路工程闸口任务搭建图.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\道路规则 2026.3.27.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\daolugongcheng\version2.0.1\main.dist\PyQt5\*"; DestDir: "{app}\PyQt5"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

